import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { adminApi, demoData } from "./services/api";
import "./styles/admin.css";

const nav = [
  ["overview", "Dashboard", "⌂"], ["destinations", "Destinations", "◆"], ["twin", "Digital Twin Status", "◉"],
  ["culture", "Cultural Stories", "✦"], ["events", "Events", "◷"], ["alerts", "Alerts", "△"],
  ["experiences", "Local Experiences", "♢"], ["analytics", "Analytics", "↗"],
];

function App() {
  const [page, setPage] = useState("overview");
  const [loggedIn, setLoggedIn] = useState(false);
  if (!loggedIn) return <Login onLogin={() => setLoggedIn(true)} />;
  return <div className="admin-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><span>Travel<span>Twin</span></span></div><p className="eyebrow">TOURISM CONTROL CENTER</p><nav>{nav.map(([id, label, icon]) => <button className={page === id ? "nav-active" : ""} key={id} onClick={() => setPage(id)}><b>{icon}</b>{label}</button>)}</nav><div className="sidebar-footer"><div className="admin-avatar">AK</div><div><strong>Admin team</strong><small>Super admin</small></div><button onClick={() => setLoggedIn(false)}>↪</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">SATURDAY · 12 SEP 2026</span><h1>{nav.find((item) => item[0] === page)?.[1]}</h1></div><div className="top-actions"><span className="live-pill"><i /> Systems operational</span><button className="icon-button">⌕</button><div className="admin-avatar">AK</div></div></header><Page page={page} setPage={setPage} /></main></div>;
}

function Login({ onLogin }) { return <div className="login-page"><div className="login-art"><div className="orbit">✦</div><p className="eyebrow">TRAVELTWIN · ADMIN</p><h1>Make every destination<br /><em>more alive.</em></h1><p>Manage the live intelligence, cultural stories and local experiences that power meaningful travel across India.</p></div><form className="login-card" onSubmit={(event) => { event.preventDefault(); onLogin(); }}><span className="brand-mark">✦</span><h2>Welcome back</h2><p>Sign in to the tourism control center.</p><label>Work email<input required type="email" defaultValue="admin@traveltwin.in" /></label><label>Password<input required type="password" defaultValue="demo1234" /></label><button className="primary full">Enter dashboard <span>→</span></button><small>Demo access · Supabase remains behind the FastAPI layer</small></form></div>; }

function Page({ page, setPage }) {
  if (page === "overview") return <Dashboard setPage={setPage} />;
  if (page === "destinations") return <Destinations />;
  if (page === "twin") return <TwinStatus />;
  if (page === "culture") return <Culture />;
  return <GenericPage title={nav.find((item) => item[0] === page)?.[1]} type={page} />;
}

function Dashboard({ setPage }) {
  const stats = [{ label: "Total destinations", value: "24", delta: "+3 this month", icon: "◆", tone: "purple" }, { label: "Active alerts", value: "08", delta: "2 need review", icon: "△", tone: "orange" }, { label: "High-crowd destinations", value: "05", delta: "Across 3 states", icon: "◉", tone: "red" }, { label: "Local experiences", value: "132", delta: "+18 verified", icon: "♢", tone: "green" }];
  return <div className="content"><div className="welcome-row"><div><p className="eyebrow">GOOD MORNING, ADMIN</p><h2>India is moving today.</h2><p className="subhead">Here is what your destination network looks like right now.</p></div><button className="primary" onClick={() => setPage("twin")}>Update live twin <span>→</span></button></div><section className="stat-grid">{stats.map((stat) => <div className="stat-card" key={stat.label}><div className={`stat-icon ${stat.tone}`}>{stat.icon}</div><p>{stat.label}</p><strong>{stat.value}</strong><small>{stat.delta}</small></div>)}</section><div className="dashboard-grid"><section className="panel wide"><PanelTitle title="Crowd status overview" action="View all" onClick={() => setPage("twin")} /><div className="crowd-chart">{[["Hampi",72,"high"],["Jaipur",88,"high"],["Varanasi",38,"low"],["Mysuru",28,"low"],["Kochi",56,"medium"]].map(([name, value, tone]) => <div className="bar-row" key={name}><span>{name}</span><div className="bar-track"><i className={tone} style={{ width: `${value}%` }} /></div><b>{tone}</b></div>)}</div></section><section className="panel"><PanelTitle title="Upcoming events" action="Manage" onClick={() => setPage("events")} /><Event name="Hampi Utsav" place="Hampi · Karnataka" date="18 OCT" /><Event name="Ganga Mahotsav" place="Varanasi · Uttar Pradesh" date="04 NOV" /><Event name="Mysuru Dasara" place="Mysuru · Karnataka" date="12 OCT" /></section><section className="panel"><PanelTitle title="Digital twin activity" action="See history" /><div className="activity"><Activity text="Hampi status updated" time="8 min ago" tone="green" /><Activity text="Alert published for Jaipur" time="26 min ago" tone="orange" /><Activity text="New craft experience verified" time="1 hr ago" tone="purple" /><Activity text="Kochi weather signal synced" time="2 hr ago" tone="blue" /></div></section><section className="panel"><PanelTitle title="Cultural engagement" action="Analytics" onClick={() => setPage("analytics")} /><div className="engagement-number"><strong>78.4%</strong><span>+12.6% <small>vs last month</small></span></div><div className="sparkline"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><p className="chart-caption">Visitors opening Culture Layer this month</p></section></div></div>;
}
function PanelTitle({ title, action, onClick }) { return <div className="panel-title"><h3>{title}</h3>{action && <button onClick={onClick}>{action} →</button>}</div>; }
function Event({ name, place, date }) { return <div className="event-row"><div className="date-box"><b>{date.split(" ")[0]}</b><small>{date.split(" ")[1]}</small></div><div><strong>{name}</strong><small>{place}</small></div><span>•••</span></div>; }
function Activity({ text, time, tone }) { return <div className="activity-row"><i className={`activity-dot ${tone}`} /><div><strong>{text}</strong><small>{time}</small></div></div>; }

function Destinations() { const [items, setItems] = useState(demoData.destinations); const [editing, setEditing] = useState(null); useEffect(() => { adminApi.list("destinations").then((response) => response.items?.length && setItems(response.items)).catch(() => {}); }, []); const save = async (form) => { const saved = { ...form, id: form.id || `demo-${Date.now()}` }; setItems((current) => form.id ? current.map((item) => item.id === form.id ? saved : item) : [saved, ...current]); setEditing(null); try { await adminApi.saveDestination(saved); } catch { /* demo mode keeps the local change visible */ } }; return <div className="content"><Toolbar title="Manage destinations" description="The places and practical details that power every TravelTwin journey." button="Add destination" onClick={() => setEditing({})} /><div className="table-panel"><div className="table-tools"><input placeholder="⌕  Search destinations" /><select><option>All states</option><option>Karnataka</option><option>Rajasthan</option></select><span>{items.length} destinations</span></div><table><thead><tr><th>Destination</th><th>Location</th><th>Best time</th><th>Entry fee</th><th>Updated</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div className="destination-cell"><div className="thumb" style={{ backgroundImage: `url(${item.image_url || item.image})` }} /><strong>{item.name}</strong></div></td><td>{item.city}, {item.state}</td><td>{item.best_time_to_visit}</td><td>₹{item.entry_fee || 0}</td><td><span className="status neutral">Published</span></td><td><button className="row-action" onClick={() => setEditing(item)}>Edit</button></td></tr>)}</tbody></table></div>{editing && <DestinationModal value={editing} onClose={() => setEditing(null)} onSave={save} />}</div>; }
function DestinationModal({ value, onClose, onSave }) { const [form, setForm] = useState(value); const change = (key, next) => setForm({ ...form, [key]: next }); return <Modal title={value.id ? "Edit destination" : "Add destination"} onClose={onClose}><div className="form-grid">{["name","city","state","description","opening_hours","entry_fee","best_time_to_visit","image_url"].map((key) => <label className={key === "description" ? "span-2" : ""} key={key}>{key.replaceAll("_", " ")}{key === "description" ? <textarea value={form[key] || ""} onChange={(e) => change(key, e.target.value)} /> : <input value={form[key] || ""} type={key === "entry_fee" ? "number" : "text"} onChange={(e) => change(key, e.target.value)} />}</label>)}</div><ModalActions onClose={onClose} onSave={() => onSave(form)} /></Modal>; }

function TwinStatus() { const [items, setItems] = useState(demoData.twin); const [editing, setEditing] = useState(null); useEffect(() => { adminApi.list("twin-status").then((response) => response.items?.length && setItems(response.items.map((item) => ({ ...item, destination: item.destination || item.destination_id })))).catch(() => {}); }, []); const save = async (form) => { setItems(items.map((item) => item.destination_id === form.destination_id ? form : item)); setEditing(null); try { await adminApi.saveTwinStatus(form); } catch {} }; return <div className="content"><Toolbar title="Digital twin status" description="Publish the signals that help travellers make a better decision right now." button="Refresh signals" onClick={() => setItems([...items])} /><div className="status-cards">{items.map((item) => <div className="twin-card" key={item.destination_id}><div className="twin-card-head"><div><p className="eyebrow">DESTINATION TWIN</p><h3>{item.destination}</h3></div><span className={`status ${item.crowd_level === "high" ? "danger" : "success"}`}>{item.crowd_level} crowd</span></div><div className="signal-list"><span>Weather <b>{item.weather_status}</b></span><span>Safety <b>{item.safety_status}</b></span><span>Route <b>{item.route_status}</b></span><span>Visit <b>{item.estimated_visit_minutes} min</b></span></div><p className="suggestion">“{item.best_suggestion}”</p><small>Nearby event · {item.nearby_cultural_event}</small><button className="outline full" onClick={() => setEditing(item)}>Edit live status</button></div>)}</div>{editing && <TwinModal value={editing} onClose={() => setEditing(null)} onSave={save} />}</div>; }
function TwinModal({ value, onClose, onSave }) { const [form, setForm] = useState(value); const change = (key, next) => setForm({ ...form, [key]: next }); return <Modal title={`Update ${value.destination}`} onClose={onClose}><div className="form-grid">{[["crowd_level",["low","medium","high"]],["weather_status",["clear","hot","rainy","storm warning"]],["safety_status",["safe","caution","unsafe"]],["route_status",["open","crowded","closed","diversion"]]].map(([key, values]) => <label key={key}>{key.replaceAll("_", " ")}<select value={form[key]} onChange={(e) => change(key, e.target.value)}>{values.map((option) => <option key={option}>{option}</option>)}</select></label>)}<label>Estimated visit time<input type="number" value={form.estimated_visit_minutes} onChange={(e) => change("estimated_visit_minutes", e.target.value)} /></label><label>Nearby cultural event<input value={form.nearby_cultural_event} onChange={(e) => change("nearby_cultural_event", e.target.value)} /></label><label className="span-2">Best current suggestion<textarea value={form.best_suggestion} onChange={(e) => change("best_suggestion", e.target.value)} /></label></div><ModalActions onClose={onClose} onSave={() => onSave(form)} /></Modal>; }

function Culture() { const [stories, setStories] = useState(demoData.stories); const [editing, setEditing] = useState(null); useEffect(() => { adminApi.list("cultural-stories").then((response) => response.items?.length && setStories(response.items)).catch(() => {}); }, []); const save = async (form) => { setStories(stories.map((item) => item.id === form.id ? form : item)); setEditing(null); try { await adminApi.saveCulture(form); } catch {} }; return <div className="content"><Toolbar title="Cultural stories" description="Keep local history, living traditions and community knowledge easy to understand." button="Add story" onClick={() => setEditing({ destination: "Hampi" })} /><div className="story-grid">{stories.map((story) => <div className="story-card" key={story.id}><div className="story-cover"><span>✦</span></div><p className="eyebrow">{story.destination}</p><h3>{story.title}</h3><p>{story.historical_importance}</p><div className="story-tags"><span>History</span><span>Tradition</span><span>Local life</span></div><button className="outline full" onClick={() => setEditing(story)}>Edit story</button></div>)}</div>{editing && <CultureModal value={editing} onClose={() => setEditing(null)} onSave={save} />}</div>; }
function CultureModal({ value, onClose, onSave }) { const [form, setForm] = useState(value); const fields = [["title","Story title"],["historical_importance","Simple history"],["local_story","Local story"],["traditions","Tradition"],["festival_connection","Festival connection"],["food_and_craft_notes","Local food and craft note"],["dos","Do’s"],["donts","Don’ts"],["explain_simply","Explain simply"]]; return <Modal title={value.id ? "Edit cultural story" : "Add cultural story"} onClose={onClose}><div className="form-grid"><label>Destination<select value={form.destination} onChange={(e) => setForm({ ...form, destination: e.target.value })}>{demoData.destinations.map((item) => <option key={item.id}>{item.name}</option>)}</select></label>{fields.map(([key, label]) => <label className="span-2" key={key}>{label}<textarea value={form[key] || ""} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}</div><ModalActions onClose={onClose} onSave={() => onSave(form)} /></Modal>; }

function GenericPage({ title, type }) { const data = demoData[type] || []; return <div className="content"><Toolbar title={`Manage ${title.toLowerCase()}`} description="A clear operating view for your tourism network." button={`Add ${title.slice(0, -1).toLowerCase()}`} onClick={() => {}} /><div className="table-panel"><div className="table-tools"><input placeholder="⌕  Search records" /><span>{data.length || 0} records</span></div>{data.length ? <table><thead><tr><th>Name</th><th>Destination</th><th>Status</th><th>Last updated</th><th /></tr></thead><tbody>{data.map((item, index) => <tr key={item.id || index}><td><strong>{item.name || item.title || item.place}</strong></td><td>{item.destination || "Hampi"}</td><td><span className="status success">Active</span></td><td>Today</td><td><button className="row-action">Edit</button></td></tr>)}</tbody></table> : <div className="empty"><span>✦</span><h3>No {title.toLowerCase()} yet</h3><p>Add your first record to make this control center useful.</p></div>}</div></div>; }
function Toolbar({ title, description, button, onClick }) { return <div className="toolbar"><div><p className="eyebrow">CONTENT MANAGEMENT</p><h2>{title}</h2><p className="subhead">{description}</p></div><button className="primary" onClick={onClick}>＋ {button}</button></div>; }
function Modal({ title, onClose, children }) { return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">TRAVELTWIN ADMIN</p><h2>{title}</h2>{children}</div></div>; }
function ModalActions({ onClose, onSave }) { return <div className="modal-actions"><button className="outline" onClick={onClose}>Cancel</button><button className="primary" onClick={onSave}>Save changes</button></div>; }

createRoot(document.getElementById("root")).render(<App />);
