import React, { useState } from "react";
import { ActivityIndicator, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppButton } from "../components/AppButton";
import { colors } from "../theme/colors";
import { askGuide } from "../services/api";

type Message = { id: string; text: string; from: "guide" | "traveller" };
const prompts = ["What should I visit next?", "Explain this place simply.", "Is this place crowded?", "Suggest local food nearby.", "Find a safer place nearby."];
export function ChatGuideScreen() {
  const [question, setQuestion] = useState(""); const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<Message[]>([{ id: "welcome", from: "guide", text: "Namaste! I’m your TravelTwin guide. Ask me what to visit, eat, understand or avoid next." }]);
  const send = async (text = question) => { if (!text.trim() || loading) return; setQuestion(""); setMessages((current) => [...current, { id: `${Date.now()}-q`, from: "traveller", text: text.trim() }]); setLoading(true); try { const answer = await askGuide(text.trim()); setMessages((current) => [...current, { id: `${Date.now()}-a`, from: "guide", text: answer }]); } catch { setMessages((current) => [...current, { id: `${Date.now()}-error`, from: "guide", text: "I’m having trouble reaching the guide. Try a calmer heritage stop or ask again in a moment." }]); } finally { setLoading(false); } };
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS === "ios" ? "padding" : undefined}><Text style={styles.kicker}>TRAVELTWIN GUIDE</Text><Text style={styles.title}>Ask about India.</Text><FlatList data={messages} keyExtractor={(item) => item.id} contentContainerStyle={styles.messages} renderItem={({ item }) => <View style={[styles.bubble, item.from === "traveller" ? styles.travellerBubble : styles.guideBubble]}><Text style={[styles.bubbleText, item.from === "traveller" && styles.travellerText]}>{item.text}</Text></View>} ListFooterComponent={loading ? <View style={styles.loading}><ActivityIndicator color={colors.indigo} /><Text style={styles.muted}>The guide is thinking…</Text></View> : null} /><View><Text style={styles.chipLabel}>TRY ASKING</Text><View style={styles.chips}>{prompts.map((prompt) => <Pressable key={prompt} onPress={() => send(prompt)} style={styles.chip}><Text style={styles.chipText}>{prompt}</Text></Pressable>)}</View><View style={styles.composer}><TextInput value={question} onChangeText={setQuestion} onSubmitEditing={() => send()} returnKeyType="send" placeholder="Ask about your next moment…" placeholderTextColor={colors.muted} style={styles.input} /><AppButton title="Send" onPress={() => send()} disabled={loading || !question.trim()} /></View></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ page: { flex: 1, padding: 20, paddingTop: 30, backgroundColor: colors.warmWhite }, kicker: { color: colors.saffron, fontSize: 10, fontWeight: "700", letterSpacing: 1.2 }, title: { color: colors.charcoal, fontSize: 30, fontWeight: "700", marginTop: 8 }, messages: { paddingVertical: 20, gap: 10 }, bubble: { maxWidth: "86%", padding: 14, borderRadius: 16 }, guideBubble: { alignSelf: "flex-start", backgroundColor: colors.indigoSoft, borderBottomLeftRadius: 4 }, travellerBubble: { alignSelf: "flex-end", backgroundColor: colors.indigo, borderBottomRightRadius: 4 }, bubbleText: { color: colors.indigo, fontSize: 13, lineHeight: 20 }, travellerText: { color: colors.white }, loading: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 8 }, muted: { color: colors.muted, fontSize: 12 }, chipLabel: { color: colors.muted, fontSize: 10, fontWeight: "700", letterSpacing: 1, marginBottom: 8 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 12 }, chip: { backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 18, paddingHorizontal: 11, paddingVertical: 9 }, chipText: { color: colors.indigo, fontSize: 11 }, composer: { flexDirection: "row", gap: 8, alignItems: "center", paddingBottom: 12 }, input: { flex: 1, backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 12, paddingHorizontal: 13, paddingVertical: 13, color: colors.charcoal } });
