import React from "react";
import { Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { AppButton } from "../components/AppButton";
import { AppCard } from "../components/AppCard";
import { StatusBadge } from "../components/StatusBadge";
import { colors } from "../theme/colors";
import { RootStackParamList } from "../navigation/AppNavigator";
export function DestinationDetailScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, "DestinationDetail">) { const { destination } = route.params; return <ScrollView contentContainerStyle={styles.page}><Image source={{ uri: destination.image }} style={styles.image} /><Text style={styles.kicker}>DESTINATION TWIN</Text><Text style={styles.title}>{destination.name}</Text><Text style={styles.location}>{destination.city}, {destination.state}</Text><Text style={styles.description}>{destination.description}</Text><AppCard><Text style={styles.cardTitle}>Live right now</Text><View style={styles.statuses}><StatusBadge label={`${destination.crowd_level} crowd`} tone="warning" /><StatusBadge label="28°C · clear" /><StatusBadge label="All clear" /></View></AppCard><View style={styles.details}><Detail label="Opening hours" value="06:00 – 18:00" /><Detail label="Entry fee" value="₹40 per person" /><Detail label="Best time" value={destination.best_time_to_visit} /></View><AppButton title="Start live guide" onPress={() => navigation.navigate("DigitalTwin", { destination })} /><AppButton title="Generate itinerary" variant="secondary" onPress={() => navigation.navigate("Planner", { destination: destination.name })} /><AppButton title="View culture layer" variant="secondary" onPress={() => navigation.navigate("Culture", { destination })} /></ScrollView>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ page: { padding: 20, paddingTop: 30, paddingBottom: 40, backgroundColor: colors.warmWhite, gap: 10 }, image: { height: 210, borderRadius: 18, width: "100%", marginBottom: 12 }, kicker: { color: colors.saffron, fontSize: 10, fontWeight: "700", letterSpacing: 1.2 }, title: { color: colors.charcoal, fontSize: 32, fontWeight: "700" }, location: { color: colors.muted, fontSize: 12 }, description: { color: colors.muted, fontSize: 14, lineHeight: 21, marginVertical: 8 }, cardTitle: { fontWeight: "700", color: colors.charcoal, marginBottom: 12 }, statuses: { flexDirection: "row", gap: 7, flexWrap: "wrap" }, details: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 8 }, detail: { flex: 1 }, detailLabel: { color: colors.muted, fontSize: 10 }, detailValue: { color: colors.charcoal, fontWeight: "700", fontSize: 12, marginTop: 5 } });
