import React, { useEffect, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { AppButton } from "../components/AppButton";
import { AppCard } from "../components/AppCard";
import { StatusBadge } from "../components/StatusBadge";
import { colors } from "../theme/colors";
import { RootStackParamList } from "../navigation/AppNavigator";
import { fetchDestinationTwin } from "../services/api";
export function DigitalTwinScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, "DigitalTwin">) { const { destination } = route.params; const [twin, setTwin] = useState<any>(); useEffect(() => { fetchDestinationTwin(destination.id).then(setTwin); }, [destination.id]); const status = twin?.status || {}; return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>LIVE DESTINATION TWIN · 10:42 AM</Text><Text style={styles.title}>Your next best moment.</Text><View style={styles.map}><Text style={styles.mapText}>MAP PLACEHOLDER</Text><Text style={styles.pin}>● You</Text><Text style={styles.route}>- - - - - - - - - - -</Text></View><AppCard style={styles.alert}><Text style={styles.alertTitle}>✦ {status.best_suggestion || "Start with the cultural highlight before peak hours."}</Text><Text style={styles.muted}>Your twin is watching crowd, weather and route changes.</Text></AppCard><View style={styles.statusRow}><StatusBadge label={`${status.crowd_level || "moderate"} crowd`} tone="warning" /><StatusBadge label={`${status.weather_status || "clear"} weather`} /><StatusBadge label={`${status.safety_status || "all clear"}`} /></View><AppCard><Text style={styles.next}>NEXT BEST PLACE</Text><Text style={styles.place}>Virupaksha Temple</Text><Text style={styles.muted}>12 min walk · Easy route · 45 min visit</Text><View style={styles.buttons}><AppButton title="Culture layer" variant="secondary" onPress={() => navigation.navigate("Culture", { destination })} /><AppButton title="Ask guide" variant="primary" onPress={() => navigation.navigate("ChatGuide")} /></View></AppCard></ScrollView>; }
const styles = StyleSheet.create({ page: { padding: 20, paddingTop: 30, paddingBottom: 40, backgroundColor: colors.warmWhite, gap: 12 }, kicker: { color: colors.saffron, fontSize: 10, fontWeight: "700", letterSpacing: 1.1 }, title: { color: colors.charcoal, fontSize: 30, fontWeight: "700", marginBottom: 8 }, map: { height: 210, borderRadius: 17, backgroundColor: "#D7E1D4", justifyContent: "center", alignItems: "center", overflow: "hidden" }, mapText: { color: "#70857A", fontSize: 11, letterSpacing: 1.5 }, pin: { position: "absolute", top: 90, left: "45%", color: colors.indigo, fontWeight: "700" }, route: { color: colors.saffron, marginTop: 20, letterSpacing: 3 }, alert: { backgroundColor: "#F8EBDD", borderColor: "#F8EBDD" }, alertTitle: { color: "#995532", fontWeight: "700", fontSize: 12, lineHeight: 17, marginBottom: 5 }, muted: { color: colors.muted, fontSize: 12, lineHeight: 18 }, statusRow: { flexDirection: "row", gap: 7, flexWrap: "wrap" }, next: { color: colors.saffron, fontSize: 10, fontWeight: "700", letterSpacing: 1 }, place: { color: colors.charcoal, fontSize: 22, fontWeight: "700", marginVertical: 7 }, buttons: { flexDirection: "row", gap: 8, marginTop: 15 }, });
