import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { AppButton } from "../components/AppButton";
import { AppCard } from "../components/AppCard";
import { TwinMetricCard } from "../components/TwinMetricCard";
import { colors } from "../theme/colors";
import { RootStackParamList } from "../navigation/AppNavigator";
import { twinStatus } from "../data/mockData";
export function HomeScreen({ navigation, route }: NativeStackScreenProps<RootStackParamList, "Home">) {
  const name = route.params?.name || "Aanya";
  return <ScrollView contentContainerStyle={styles.page}><View style={styles.header}><View><Text style={styles.kicker}>SATURDAY · 12 SEP 2026</Text><Text style={styles.greeting}>Good morning, {name}</Text><Text style={styles.muted}>Your day in Hampi is looking beautiful.</Text></View><Text style={styles.avatar}>AS</Text></View><AppCard style={styles.twinCard}><Text style={styles.badge}>LIVE DESTINATION TWIN</Text><Text style={styles.heroTitle}>Hampi, in your rhythm.</Text><Text style={styles.heroCopy}>Three experiences tuned to your cultural explorer twin.</Text><AppButton title="Open live guide" onPress={() => navigation.navigate("DigitalTwin", { destination: { id: "hampi", name: "Hampi", city: "Hosapete", state: "Karnataka", description: "Vijayanagara ruins, boulders and river stories.", best_time_to_visit: "Oct – Feb", crowd_level: "Moderate", image: "https://images.unsplash.com/photo-1600100397608-f0107e2e5e9b?w=900" } })} /></AppCard><Text style={styles.heading}>Your twin today</Text><View style={styles.metrics}><TwinMetricCard icon="☼" label="Weather" value={twinStatus.weather} /><TwinMetricCard icon="◉" label="Crowd" value={twinStatus.crowd} /><TwinMetricCard icon="✓" label="Safety" value={twinStatus.safety} /></View><AppCard style={styles.highlight}><Text style={styles.kicker}>CULTURAL HIGHLIGHT</Text><Text style={styles.highlightTitle}>The stone chariot’s hidden story</Text><Text style={styles.muted}>Its wheels were once designed to spin.</Text></AppCard><Text style={styles.heading}>Make today yours</Text><View style={styles.actions}><AppButton title="Plan trip" onPress={() => navigation.navigate("Planner")} /><AppButton title="Explore destinations" variant="secondary" onPress={() => navigation.navigate("Destinations")} /><AppButton title="Ask AI guide" variant="secondary" onPress={() => navigation.navigate("ChatGuide")} /><AppButton title="Safety & offline" variant="secondary" onPress={() => navigation.navigate("Safety")} /></View></ScrollView>;
}
const styles = StyleSheet.create({ page: { padding: 20, paddingTop: 30, paddingBottom: 40, backgroundColor: colors.warmWhite }, header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 22 }, kicker: { color: colors.saffron, fontSize: 10, fontWeight: "700", letterSpacing: 1.1 }, greeting: { fontSize: 24, fontWeight: "700", color: colors.charcoal, marginVertical: 5 }, muted: { color: colors.muted, fontSize: 12, lineHeight: 18 }, avatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#E8D0B8", textAlign: "center", textAlignVertical: "center", overflow: "hidden", color: "#654437", fontWeight: "700", fontSize: 12 }, twinCard: { backgroundColor: colors.indigo, borderColor: colors.indigo, marginBottom: 22 }, badge: { color: "#DDE0FF", fontSize: 9, fontWeight: "700", letterSpacing: 1 }, heroTitle: { color: colors.white, fontSize: 28, fontWeight: "700", marginVertical: 15 }, heroCopy: { color: "#D9DBF1", fontSize: 12, marginBottom: 18 }, heading: { color: colors.charcoal, fontSize: 16, fontWeight: "700", marginBottom: 11 }, metrics: { flexDirection: "row", gap: 8, marginBottom: 14 }, highlight: { backgroundColor: colors.sand, borderColor: colors.sand, marginBottom: 22 }, highlightTitle: { color: colors.charcoal, fontWeight: "700", fontSize: 14, marginVertical: 7 }, actions: { gap: 9 } });
