import React, { useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { AppButton } from "../components/AppButton";
import { ItineraryCard } from "../components/ItineraryCard";
import { colors } from "../theme/colors";
import { RootStackParamList } from "../navigation/AppNavigator";
import { generateItinerary } from "../services/api";
export function PlannerScreen({ route }: NativeStackScreenProps<RootStackParamList, "Planner">) { const [destination, setDestination] = useState(route.params?.destination || "Hampi"); const [days, setDays] = useState(1); const [budget, setBudget] = useState("Medium"); const [pace, setPace] = useState("Balanced"); const [result, setResult] = useState<any>(); const [loading, setLoading] = useState(false); const run = async () => { setLoading(true); try { setResult(await generateItinerary({ user_id: "demo-user", destination, days, budget, travel_pace: pace, interests: ["Temples", "Food"], walking_comfort: "Medium" })); } finally { setLoading(false); } }; return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>AI TRIP PLANNER</Text><Text style={styles.title}>Build a day that feels like you.</Text><Text style={styles.copy}>Rule-based intelligence now. Real AI later.</Text><Text style={styles.label}>Destination</Text><View style={styles.select}><Text style={styles.selectText}>{destination}</Text></View><Text style={styles.label}>Number of days</Text><View style={styles.row}>{[1, 2, 3].map(value => <Text key={value} onPress={() => setDays(value)} style={[styles.choice, days === value && styles.active]}>{value} day{value > 1 ? "s" : ""}</Text>)}</View><Text style={styles.label}>Budget range</Text><View style={styles.row}>{["Low", "Medium", "Premium"].map(value => <Text key={value} onPress={() => setBudget(value)} style={[styles.choice, budget === value && styles.active]}>{value}</Text>)}</View><Text style={styles.label}>Travel pace</Text><View style={styles.row}>{["Relaxed", "Balanced", "Full day"].map(value => <Text key={value} onPress={() => setPace(value)} style={[styles.choice, pace === value && styles.active]}>{value}</Text>)}</View><AppButton title={loading ? "Tuning your day..." : "Generate smart itinerary"} onPress={run} disabled={loading} />{result && <View style={styles.result}><Text style={styles.resultTitle}>{result.summary}</Text>{result.items.map((day: any) => <View key={day.day}><Text style={styles.day}>DAY {day.day}</Text>{day.items.map((item: any) => <ItineraryCard key={item.time_slot} item={item} />)}</View>)}</View>}</ScrollView>; }
const styles = StyleSheet.create({ page: { padding: 20, paddingTop: 30, paddingBottom: 45, backgroundColor: colors.warmWhite }, kicker: { color: colors.saffron, fontSize: 10, fontWeight: "700", letterSpacing: 1.2 }, title: { color: colors.charcoal, fontSize: 30, fontWeight: "700", marginTop: 8 }, copy: { color: colors.muted, fontSize: 13, marginTop: 5, marginBottom: 24 }, label: { color: colors.charcoal, fontWeight: "700", fontSize: 13, marginTop: 16, marginBottom: 8 }, select: { backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 12, padding: 14 }, selectText: { color: colors.charcoal, fontSize: 13 }, row: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, choice: { backgroundColor: colors.white, color: colors.muted, borderColor: colors.line, borderWidth: 1, paddingVertical: 10, paddingHorizontal: 13, borderRadius: 18, fontSize: 11 }, active: { color: colors.indigo, backgroundColor: colors.indigoSoft, borderColor: colors.indigo, fontWeight: "700" }, result: { marginTop: 25 }, resultTitle: { color: colors.indigo, backgroundColor: colors.indigoSoft, padding: 13, borderRadius: 12, fontSize: 12, lineHeight: 18, marginBottom: 16 }, day: { color: colors.charcoal, fontWeight: "700", fontSize: 13, letterSpacing: 1, marginBottom: 9 } });
