import React, { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppButton } from "../components/AppButton";
import { AppCard } from "../components/AppCard";
import { colors } from "../theme/colors";

export function SafetyScreen() {
  const [sosVisible, setSosVisible] = useState(false);
  const confirmSos = () => Alert.alert("SOS ready", "For immediate emergency help in India, call 112. TravelTwin has prepared your destination and offline itinerary details.", [{ text: "Close", onPress: () => setSosVisible(false) }]);
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>TRAVELTWIN · SAFETY & OFFLINE</Text><Text style={styles.title}>Calm, clear help when you need it.</Text><Text style={styles.copy}>Your key travel information stays easy to find, even when connectivity is uncertain.</Text>
    <View style={styles.sos}><Text style={styles.sosText}>SOS</Text><Text style={styles.sosSub}>Tap for emergency information</Text></View><AppButton title="Emergency contacts · 112" variant="danger" onPress={() => Alert.alert("Emergency help", "India emergency number: 112\nPolice: 100\nAmbulance: 108")} /><AppButton title="Activate SOS information" variant="secondary" onPress={() => setSosVisible(true)} />
    <AppCard><Text style={styles.cardTitle}>NEARBY HELP</Text><Text style={styles.helpName}>Hosapete Police Help Desk</Text><Text style={styles.copy}>Verified help point placeholder · Ask the guide for directions.</Text></AppCard>
    <AppCard><Text style={styles.cardTitle}>ACTIVE SAFETY ALERTS</Text><Text style={styles.copy}>No active alerts. Last destination sync: just now.</Text></AppCard>
    <AppCard style={styles.offline}><Text style={styles.cardTitle}>OFFLINE SAVED ITINERARY</Text><Text style={styles.helpName}>Hampi cultural half-day</Text><Text style={styles.copy}>4 saved places · emergency contacts · route notes available offline.</Text></AppCard>
    <Text style={styles.section}>Travel safety tips</Text><Tip text="Carry water, sun protection and a charged phone." /><Tip text="Use marked paths and verified local guides after sunset." /><Tip text="Keep valuables secure in busy temple and market areas." />
    <AppCard style={styles.dos}><Text style={styles.cardTitle}>LOCAL DO’S & DON’TS</Text><Text style={styles.copy}>Do dress respectfully and ask before photographing people. Don’t touch monuments or block ceremonies.</Text></AppCard>
    {sosVisible && <View style={styles.modal}><Text style={styles.modalTitle}>SOS information is ready</Text><Text style={styles.copy}>Call 112 for immediate emergency support. Your saved itinerary and destination details can help you explain where you are.</Text><AppButton title="I understand" onPress={confirmSos} /></View>}
  </ScrollView>;
}
function Tip({ text }: { text: string }) { return <View style={styles.tip}><Text style={styles.check}>✓</Text><Text style={styles.copy}>{text}</Text></View>; }
const styles = StyleSheet.create({ page: { padding: 20, paddingTop: 30, paddingBottom: 45, gap: 12, backgroundColor: colors.warmWhite }, kicker: { color: colors.saffron, fontSize: 10, fontWeight: "700", letterSpacing: 1.2 }, title: { color: colors.charcoal, fontSize: 29, fontWeight: "700", lineHeight: 36, marginTop: 2 }, copy: { color: colors.muted, fontSize: 13, lineHeight: 20 }, sos: { width: 145, height: 145, borderRadius: 73, backgroundColor: colors.danger, alignSelf: "center", justifyContent: "center", alignItems: "center", marginVertical: 15 }, sosText: { color: colors.white, fontWeight: "700", fontSize: 30, letterSpacing: 2 }, sosSub: { color: colors.white, fontSize: 10, width: 95, textAlign: "center", marginTop: 8 }, cardTitle: { color: colors.emerald, fontWeight: "700", fontSize: 10, letterSpacing: 1, marginBottom: 8 }, helpName: { color: colors.charcoal, fontSize: 15, fontWeight: "700", marginBottom: 5 }, offline: { backgroundColor: colors.indigoSoft, borderColor: colors.indigoSoft }, section: { color: colors.charcoal, fontWeight: "700", fontSize: 16, marginTop: 6 }, tip: { flexDirection: "row", gap: 10, alignItems: "flex-start" }, check: { color: colors.emerald, fontSize: 17, fontWeight: "700" }, dos: { backgroundColor: colors.sand, borderColor: colors.sand }, modal: { backgroundColor: colors.white, borderColor: colors.danger, borderWidth: 1, borderRadius: 16, padding: 16, gap: 12 }, modalTitle: { color: colors.danger, fontWeight: "700", fontSize: 17 } });
