import React, { useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { AppButton } from "../components/AppButton";
import { colors } from "../theme/colors";
import { spacing } from "../theme/spacing";
import { RootStackParamList } from "../navigation/AppNavigator";
import { saveTravellerProfile } from "../services/api";
const stylesList = ["Relaxed", "Adventure", "Cultural", "Family", "Spiritual", "Budget"];
const interestsList = ["Forts", "Temples", "Food", "Crafts", "Nature", "Festivals", "Museums"];
const languages = ["English", "Hindi", "Kannada", "Tamil", "Telugu", "Malayalam"];
function Chips({ values, selected, onSelect, multi = false }: { values: string[]; selected: string | string[]; onSelect: (value: string) => void; multi?: boolean }) { return <View style={styles.chips}>{values.map(value => { const active = multi ? (selected as string[]).includes(value) : selected === value; return <Text key={value} onPress={() => onSelect(value)} style={[styles.chip, active && styles.chipActive]}>{value}</Text>; })}</View>; }
export function TravellerTwinScreen({ navigation }: NativeStackScreenProps<RootStackParamList, "TravellerTwin">) {
  const [name, setName] = useState(""); const [style, setStyle] = useState("Cultural"); const [interests, setInterests] = useState<string[]>(["Temples", "Food"]); const [budget, setBudget] = useState("Medium"); const [walking, setWalking] = useState("Medium"); const [language, setLanguage] = useState("English"); const [safety, setSafety] = useState("No special preference");
  const toggleInterest = (value: string) => setInterests(current => current.includes(value) ? current.filter(item => item !== value) : [...current, value]);
  const submit = async () => { try { await saveTravellerProfile({ user_id: "demo-user", display_name: name || "Aanya", travel_style: style.toLowerCase(), interests, budget_range: budget.toLowerCase(), walking_comfort: walking.toLowerCase(), language_preference: language, safety_preference: safety }); } catch { /* Demo mode can continue without the API. */ } navigation.navigate("Home", { name: name || "Aanya" }); };
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>YOUR TRAVELLER TWIN</Text><Text style={styles.title}>Travel like you.</Text><Text style={styles.copy}>A few choices help your twin find moments made for your pace.</Text><TextInput value={name} onChangeText={setName} placeholder="What should we call you?" placeholderTextColor={colors.muted} style={styles.input} /><Section title="Travel style"><Chips values={stylesList} selected={style} onSelect={setStyle} /></Section><Section title="What sparks your curiosity?"><Chips values={interestsList} selected={interests} onSelect={toggleInterest} multi /></Section><Section title="Budget range"><Chips values={["Low", "Medium", "Premium"]} selected={budget} onSelect={setBudget} /></Section><Section title="Walking comfort"><Chips values={["Low", "Medium", "High"]} selected={walking} onSelect={setWalking} /></Section><Section title="Preferred language"><Chips values={languages} selected={language} onSelect={setLanguage} /></Section><Section title="Safety preference"><Chips values={["Avoid crowded places", "Prefer family-safe routes", "Prefer short routes", "No special preference"]} selected={safety} onSelect={setSafety} /></Section><AppButton title="Save my Traveller Twin" onPress={submit} /></ScrollView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
const styles = StyleSheet.create({ page: { padding: spacing.page, paddingBottom: 40, backgroundColor: colors.warmWhite }, kicker: { color: colors.saffron, fontWeight: "700", letterSpacing: 1.4, fontSize: 10, marginTop: 20 }, title: { color: colors.charcoal, fontSize: 32, fontWeight: "700", marginTop: 8 }, copy: { color: colors.muted, lineHeight: 20, marginTop: 6, marginBottom: 18 }, input: { backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 12, padding: 14, fontSize: 13 }, section: { borderTopWidth: 1, borderTopColor: colors.line, paddingVertical: 17 }, sectionTitle: { fontWeight: "700", color: colors.charcoal, fontSize: 14, marginBottom: 11 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, chip: { backgroundColor: colors.white, borderColor: colors.line, borderWidth: 1, borderRadius: 18, color: colors.muted, paddingVertical: 9, paddingHorizontal: 12, fontSize: 11 }, chipActive: { backgroundColor: colors.indigoSoft, borderColor: colors.indigo, color: colors.indigo, fontWeight: "700" } });
